<a href="https://colab.research.google.com/github/AnnabelleMcSharry/AI-ML-Car-Data/blob/main/Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import pandas as pd

Cars= pd.read_csv("CarDataset.csv",index_col=False, names = ["S.No.", "Name", "Location", "Year", "Kilometers_Driven", "Fuel_Type", "Transmission", "Owner_Type", "Mileage", "Engine"])

print(Cars.head())

   S.No.                              Name  Location  Year  Kilometers_Driven  \
0  S.No.                              Name  Location  Year  Kilometers_Driven
1      0            Maruti Wagon R LXI CNG    Mumbai  2010              72000
2      1  Hyundai Creta 1.6 CRDi SX Option      Pune  2015              41000
3      2                      Honda Jazz V   Chennai  2011              46000
4      3                 Maruti Ertiga VDI   Chennai  2012              87000

   Fuel_Type  Transmission  Owner_Type     Mileage   Engine
0  Fuel_Type  Transmission  Owner_Type     Mileage   Engine
1        CNG        Manual       First  26.6 km/kg   998 CC
2     Diesel        Manual       First  19.67 kmpl  1582 CC
3     Petrol        Manual       First   18.2 kmpl  1199 CC
4     Diesel        Manual       First  20.77 kmpl  1248 CC

In [68]:
Cars = Cars.drop(["S.No."], axis=1)
print(Cars.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7254 entries, 0 to 7253
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               7254 non-null   object
 1   Location           7254 non-null   object
 2   Year               7254 non-null   object
 3   Kilometers_Driven  7254 non-null   object
 4   Fuel_Type          7254 non-null   object
 5   Transmission       7254 non-null   object
 6   Owner_Type         7254 non-null   object
 7   Mileage            7252 non-null   object
 8   Engine             7208 non-null   object
dtypes: object(9)
memory usage: 510.2+ KB
None

In [69]:
Cars = Cars.replace(" ", pd.NA)
print(Cars.isnull().sum())

Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               2
Engine               46
dtype: int64

In [70]:
new_Cars = Cars.dropna()
print("################")
print("Total records that would be lost if deleted : ")
print(Cars.shape[0]- new_Cars.shape[0])
del new_Cars

################
Total records that would be lost if deleted :
48

In [71]:
print(Cars['Mileage'].value_counts())
print(Cars['Engine'].value_counts())

Mileage
17.0 kmpl     207
18.9 kmpl     201
18.6 kmpl     144
21.1 kmpl     106
20.36 kmpl    105
             ...
13.44 kmpl      1
23.57 kmpl      1
8.77 kmpl       1
15.56 kmpl      1
17.15 kmpl      1
Name: count, Length: 451, dtype: int64
Engine
1197 CC    732
1248 CC    610
1498 CC    370
998 CC     309
1198 CC    281
          ...
2112 CC      1
2000 CC      1
1795 CC      1
3696 CC      1
1389 CC      1
Name: count, Length: 151, dtype: int64

In [72]:
Cars = Cars.dropna()

In [73]:
Cars = Cars.iloc[1:].copy() # Drop the first row (the duplicate header)
display(Cars.head()) # Display to confirm the header row is removed

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine
1,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC
2,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC
3,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC
4,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC
5,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC

In [74]:
Cars["Year"] = pd.to_numeric(Cars["Year"])

In [75]:
Cars["Kilometers_Driven"] = pd.to_numeric(Cars["Kilometers_Driven"])

In [76]:
print('Unique units in Mileage:')
print(Cars['Mileage'].apply(lambda x: str(x).split()[-1]).unique())

print('\nUnique units in Engine:')
print(Cars['Engine'].apply(lambda x: str(x).split()[-1]).unique())

Unique units in Mileage:
['km/kg' 'kmpl']

Unique units in Engine:
['CC']

In [77]:
print('Count of each unit in Mileage:')
print(Cars['Mileage'].apply(lambda x: str(x).split()[-1]).value_counts())

Count of each unit in Mileage:
Mileage
kmpl     7131
km/kg      74
Name: count, dtype: int64

In [78]:
print(Cars['Fuel_Type'].unique())

['CNG' 'Diesel' 'Petrol' 'LPG']

In [79]:
Cars = Cars.replace("CNG", pd.NA)
Cars = Cars.replace("LPG", pd.NA)
print(Cars.isnull().sum())

Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type            74
Transmission          0
Owner_Type            0
Mileage               0
Engine                0
dtype: int64

In [80]:
Cars = Cars.dropna()

In [81]:
print('Count of each unit in Mileage:')
print(Cars['Mileage'].apply(lambda x: str(x).split()[-1]).value_counts())

Count of each unit in Mileage:
Mileage
kmpl    7131
Name: count, dtype: int64

In [82]:
Cars = Cars.rename(columns={'Mileage': 'Mileage_kmpl'})

In [83]:
Cars['Mileage_kmpl'] = Cars['Mileage_kmpl'].astype(str).str.split().str[0].astype(float)
display(Cars.head())

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage_kmpl,Engine
2,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582 CC
3,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199 CC
4,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248 CC
5,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968 CC
7,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08,1461 CC

In [84]:
Cars = Cars.rename(columns={'Engine': 'Engine_CC'})

In [85]:
Cars['Engine_CC'] = Cars['Engine_CC'].astype(str).str.split().str[0].astype(int)
display(Cars.head())

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage_kmpl,Engine_CC
2,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582
3,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199
4,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248
5,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968
7,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08,1461

In [86]:
print('Unique values and counts for Fuel_Type:')
print(Cars['Fuel_Type'].value_counts())

print('\nUnique values and counts for Transmission:')
print(Cars['Transmission'].value_counts())

print('\nUnique values and counts for Owner_Type:')
print(Cars['Owner_Type'].value_counts())

# For Name and Location, we'll just show the number of unique values due to potentially high cardinality
print('\nNumber of unique car names:', Cars['Name'].nunique())
print('Number of unique locations:', Cars['Location'].nunique())

Unique values and counts for Fuel_Type:
Fuel_Type
Diesel    3840
Petrol    3291
Name: count, dtype: int64

Unique values and counts for Transmission:
Transmission
Manual       5095
Automatic    2036
Name: count, dtype: int64

Unique values and counts for Owner_Type:
Owner_Type
First             5864
Second            1123
Third              133
Fourth & Above      11
Name: count, dtype: int64

Number of unique car names: 1990
Number of unique locations: 11

Based on the unique values:

*   **Fuel_Type**, **Transmission**, and **Location** are nominal categories with low cardinality. **One-Hot Encoding** is the best choice here as it creates new binary columns for each category, avoiding any implied ordinal relationship.
*   **Owner_Type** is an ordinal category ('First', 'Second', 'Third'). **Label Encoding** is suitable as it assigns numerical values (e.g., 0, 1, 2) that preserve the inherent order.
*   **Name** has high cardinality (many unique values). For this, **Label Encoding** can be used to convert it to a numerical representation. While Label Encoding introduces an arbitrary ordinal relationship, it is a practical approach for high-cardinality nominal features to avoid creating an excessively sparse DataFrame if One-Hot Encoding were used.

In [87]:
# One-Hot Encoding for 'Fuel_Type', 'Transmission', and 'Location' (Nominal)
# We are not using `drop_first=True` to ensure explicit columns for all categories.
Cars = pd.get_dummies(Cars, columns=['Fuel_Type', 'Transmission', 'Location'], drop_first=False)

display(Cars.head())

,Name,Year,Kilometers_Driven,Owner_Type,Mileage_kmpl,Engine_CC,Fuel_Type_Diesel,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,...,Location_Bangalore,Location_Chennai,Location_Coimbatore,Location_Delhi,Location_Hyderabad,Location_Jaipur,Location_Kochi,Location_Kolkata,Location_Mumbai,Location_Pune
2,Hyundai Creta 1.6 CRDi SX Option,2015,41000,First,19.67,1582,True,False,False,True,...,False,False,False,False,False,False,False,False,False,True
3,Honda Jazz V,2011,46000,First,18.20,1199,False,True,False,True,...,False,True,False,False,False,False,False,False,False,False
4,Maruti Ertiga VDI,2012,87000,First,20.77,1248,True,False,False,True,...,False,True,False,False,False,False,False,False,False,False
5,Audi A4 New 2.0 TDI Multitronic,2013,40670,Second,15.20,1968,True,False,True,False,...,False,False,True,False,False,False,False,False,False,False
7,Nissan Micra Diesel XV,2013,86999,First,23.08,1461,True,False,False,True,...,False,False,False,False,False,True,False,False,False,False

In [88]:
owner_type_mapping = {'First': 0, 'Second': 1, 'Third': 2, 'Fourth & Above': 3}
Cars['Owner_Type_Encoded'] = Cars['Owner_Type'].map(owner_type_mapping)

display(Cars[['Owner_Type', 'Owner_Type_Encoded']].head())

  Owner_Type  Owner_Type_Encoded
2      First                   0
3      First                   0
4      First                   0
5     Second                   1
7      First                   0

In [89]:
Cars = Cars.drop('Owner_Type', axis=1)
display(Cars.head())

,Name,Year,Kilometers_Driven,Mileage_kmpl,Engine_CC,Fuel_Type_Diesel,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Location_Ahmedabad,...,Location_Chennai,Location_Coimbatore,Location_Delhi,Location_Hyderabad,Location_Jaipur,Location_Kochi,Location_Kolkata,Location_Mumbai,Location_Pune,Owner_Type_Encoded
2,Hyundai Creta 1.6 CRDi SX Option,2015,41000,19.67,1582,True,False,False,True,False,...,False,False,False,False,False,False,False,False,True,0
3,Honda Jazz V,2011,46000,18.20,1199,False,True,False,True,False,...,True,False,False,False,False,False,False,False,False,0
4,Maruti Ertiga VDI,2012,87000,20.77,1248,True,False,False,True,False,...,True,False,False,False,False,False,False,False,False,0
5,Audi A4 New 2.0 TDI Multitronic,2013,40670,15.20,1968,True,False,True,False,False,...,False,True,False,False,False,False,False,False,False,1
7,Nissan Micra Diesel XV,2013,86999,23.08,1461,True,False,False,True,False,...,False,False,False,False,True,False,False,False,False,0

In [90]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Apply Label Encoding to the 'Name' column
Cars['Name_Encoded'] = label_encoder.fit_transform(Cars['Name'])

# Display the original and encoded columns
display(Cars[['Name', 'Name_Encoded']].head())

                               Name  Name_Encoded
2  Hyundai Creta 1.6 CRDi SX Option           552
3                      Honda Jazz V           523
4                 Maruti Ertiga VDI          1129
5   Audi A4 New 2.0 TDI Multitronic            23
7            Nissan Micra Diesel XV          1453

In [91]:
Cars = Cars.drop('Name', axis=1)
display(Cars.head())

,Year,Kilometers_Driven,Mileage_kmpl,Engine_CC,Fuel_Type_Diesel,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Location_Ahmedabad,Location_Bangalore,...,Location_Coimbatore,Location_Delhi,Location_Hyderabad,Location_Jaipur,Location_Kochi,Location_Kolkata,Location_Mumbai,Location_Pune,Owner_Type_Encoded,Name_Encoded
2,2015,41000,19.67,1582,True,False,False,True,False,False,...,False,False,False,False,False,False,False,True,0,552
3,2011,46000,18.20,1199,False,True,False,True,False,False,...,False,False,False,False,False,False,False,False,0,523
4,2012,87000,20.77,1248,True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,0,1129
5,2013,40670,15.20,1968,True,False,True,False,False,False,...,True,False,False,False,False,False,False,False,1,23
7,2013,86999,23.08,1461,True,False,False,True,False,False,...,False,False,False,True,False,False,False,False,0,1453